# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule: 
    - cron: '10 * * * *'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        ref: runner

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
          python-version: "3.10"
    - name: Install dependencies
      run: |
          pip install requests
    - name: Test with metro_data
      run: |
          python metro_data.py
    - name: commit
      run: |
          git config --local user.name "CarmeloChou"
          git config --local user.email "554375635@qq.com"
          git add "*.txt" 
          git commit -m "update runner" 
          git push -u origin runner

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          branch: runner
